/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unijena_bioinf_TreeVisualization_TreeVisualizer */

#ifndef _Included_de_unijena_bioinf_TreeVisualization_TreeVisualizer
#define _Included_de_unijena_bioinf_TreeVisualization_TreeVisualizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unijena_bioinf_TreeVisualization_TreeVisualizer
 * Method:    LayoutFromEdgeList_internal
 * Signature: (I[I[I[FI)[[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_unijena_bioinf_TreeVisualization_TreeVisualizer_LayoutFromEdgeList_1internal
  (JNIEnv *, jobject, jint, jintArray, jintArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
